// <auto-generated />
using AboneApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AboneApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200511230244_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("AboneApp.API.Models.Abone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<int>("SozlesmeNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TCKimlikNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Abones");
                });
#pragma warning restore 612, 618
        }
    }
}
